import const

const.URLWRITEKEY = "URLWRITEKEY"
const.URLPOOLKEY = "URLPOOLKEY"
const.PROCESSPOOLWRITEKEY = "PROCESSPOOLWRITEKEY"
const.PROCESSPOOLCOUNTKEY = "PROCESSPOOLCOUNTKEY"
const.PROCESSPOOLKEY = "PROCESSPOOLKEY"
